# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/mips_cpu/mips_cpu.cache/wt [current_project]
set_property parent.project_path D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/mips_cpu/mips_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/mips_cpu/mips_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/circuit/ALU.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/AND_GATE.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/AND_GATE_10_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/AND_GATE_5_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/AND_GATE_6_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/AND_GATE_7_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/AND_GATE_8_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/arithmetic/Adder.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/wiring/Bit_Extender_12_32_SIGN.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/wiring/Bit_Extender_20_32_SIGN.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/wiring/Bit_Extender_8_32.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/circuit/Control.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/circuit/Control_2.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/circuit/Control_op.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/io/Counter.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/io/FPGADigit.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/plexers/Multiplexer_bus_2.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/NOT_GATE.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/OR_GATE.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/OR_GATE_12_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/OR_GATE_20_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/OR_GATE_6_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/gates/OR_GATE_8_INPUTS.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/memory/RAM_RAM.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/memory/REGISTER_FLIP_FLOP_PC.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/memory/ROM_ROM.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/circuit/RegFile.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/circuit/RiscV_DataPath.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/arithmetic/Shifter_12_bit.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/arithmetic/Shifter_20_bit.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/io/decoder3_8.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/io/display_sel.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/io/divider.v
  D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/verilog/io/sevenseg_dec.v
  D:/MyFile/code/Vivado/project_1/project_1.srcs/sources_1/new/circuit/RiscV_Top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/xdc/LogisimToplevelShell.xdc
set_property used_in_implementation false [get_files D:/MyFile/code/Vivado/Risc_V2/cpu21-riscv/RiscV/xdc/LogisimToplevelShell.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RiscV_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RiscV_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RiscV_Top_utilization_synth.rpt -pb RiscV_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
